name: testing github actions

on:
  push:
    branches:
      - master
      - develop
      - feature/*

jobs:
  run-test:
    name: running tests
    runs-on: ubuntu-latest
    env:
      FOO: bar-baz
    steps:
      - name: Setup Golang Environment
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.23.1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show env
        run: make env
      - name: Show event json
        run: cat ${GITHUB_EVENT_PATH}
      - name: Run tests
        run: make test
      - name: Create coverage report
        run: make cover

      - name: Save report
        uses: actions/upload-artifact@v4.3.2
        with:
          name: coverage-report
          path: build/cover.html
